version: "3.9"
services:
  web:
    image: yieldguru-frontend
    container_name: yieldguru-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    volumes:
      - './frontend:/app'
    networks:
      - yieldguru

networks:
  yieldguru:
    driver: bridge