version: "3.9"
services:
  web:
    image: yieldguru-frontend
    container_name: yieldguru-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    volumes:
      - './frontend:/app'
    networks:
      - yieldguru
  web-admin:
    image: yieldguru-admin-frontend
    container_name: yieldguru-admin-frontend
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:5173"
    volumes:
      - './admin-frontend:/app'
    networks:
      - yieldguru

networks:
  yieldguru:
    driver: bridge